"""Add cascade delete for likes on posts

Revision ID: 256d6071644b
Revises: 9cfc96c8742c
Create Date: 2026-03-29 17:29:17.397428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '256d6071644b'
down_revision: Union[str, None] = '9cfc96c8742c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing foreign key constraint
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')

    # Add new foreign key with CASCADE DELETE
    op.create_foreign_key(
        'likes_post_id_fkey',
        'likes',
        'posts',
        ['post_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the cascading foreign key
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')

    # Restore the original foreign key without CASCADE
    op.create_foreign_key(
        'likes_post_id_fkey',
        'likes',
        'posts',
        ['post_id'],
        ['id']
    )
    # ### end Alembic commands ###