"""add_user_snapshot_to_posts

Revision ID: 36696b9825b5
Revises: 567154b4c8ad
Create Date: 2026-03-04 17:43:47.524931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36696b9825b5'
down_revision: Union[str, None] = '567154b4c8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # まずNULL可能で追加
    op.add_column('posts', sa.Column('author_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('author_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('author_gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('author_age_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # 既存データに対してユーザー情報で初期化
    op.execute("""
        UPDATE posts
        SET
            author_status = users.status,
            author_nickname = users.nickname,
            author_gender = users.gender,
            author_age_range = users.age_range
        FROM users
        WHERE posts.user_id = users.id
    """)

    # NOT NULL制約を追加
    op.alter_column('posts', 'author_status', nullable=False)
    op.alter_column('posts', 'author_nickname', nullable=False)
    op.alter_column('posts', 'author_gender', nullable=False)
    op.alter_column('posts', 'author_age_range', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_age_range')
    op.drop_column('posts', 'author_gender')
    op.drop_column('posts', 'author_nickname')
    op.drop_column('posts', 'author_status')
    # ### end Alembic commands ###