"""add missing posts columns

Revision ID: 4ced072b4d53
Revises: 622b8a65ea7b
Create Date: 2026-03-07 18:41:35.927959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ced072b4d53'
down_revision: Union[str, None] = '622b8a65ea7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with nullable=True first for existing data
    op.add_column('posts', sa.Column('author_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('author_age_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('author_avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE posts SET author_status = 'seeking' WHERE author_status IS NULL")
    op.execute("UPDATE posts SET author_age_range = '20s' WHERE author_age_range IS NULL")
    op.execute("UPDATE posts SET likes_count = 0 WHERE likes_count IS NULL")

    # Now make the required columns NOT NULL
    op.alter_column('posts', 'author_status', nullable=False)
    op.alter_column('posts', 'author_age_range', nullable=False)
    op.alter_column('posts', 'likes_count', nullable=False)

    # Add missing user columns if they don't exist
    try:
        op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    except:
        pass  # Column might already exist

    try:
        op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=True))
        op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=True))

        # Set defaults
        op.execute("UPDATE users SET followers_count = 0 WHERE followers_count IS NULL")
        op.execute("UPDATE users SET following_count = 0 WHERE following_count IS NULL")

        # Make NOT NULL
        op.alter_column('users', 'followers_count', nullable=False)
        op.alter_column('users', 'following_count', nullable=False)
    except:
        pass  # Columns might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes_count')
    op.drop_column('posts', 'author_avatar_url')
    op.drop_column('posts', 'author_age_range')
    op.drop_column('posts', 'author_status')

    try:
        op.drop_column('users', 'following_count')
        op.drop_column('users', 'followers_count')
        op.drop_column('users', 'avatar_url')
    except:
        pass  # Columns might not exist
    # ### end Alembic commands ###