"""initial_tables

Revision ID: 567154b4c8ad
Revises:
Create Date: 2026-03-04 16:05:15.279666

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "567154b4c8ad"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_LOVE", "HEARTBROKEN", "SEEKING", name="userstatus"),
            nullable=False,
        ),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", "PRIVATE", name="gender"), nullable=False
        ),
        sa.Column(
            "age_range",
            sa.Enum("TEENS", "TWENTIES", "THIRTIES", "FORTIES", "FIFTIES_PLUS", name="agerange"),
            nullable=False,
        ),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "posts",
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.create_table(
        "replies",
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_replies_post_id"), "replies", ["post_id"], unique=False)
    op.create_index(op.f("ix_replies_user_id"), "replies", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_replies_user_id"), table_name="replies")
    op.drop_index(op.f("ix_replies_post_id"), table_name="replies")
    op.drop_table("replies")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
