"""add phase 2 features

Revision ID: 711b57c0bef5
Revises: 86deffe96aa3
Create Date: 2026-03-04 21:17:31.153513

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "711b57c0bef5"
down_revision: str | None = "86deffe96aa3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("author_avatar_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    )

    # Add likes_count with default value
    op.add_column(
        "posts", sa.Column("likes_count", sa.Integer(), nullable=False, server_default="0")
    )

    op.add_column(
        "users",
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    )

    # Add follow counts with default values
    op.add_column(
        "users", sa.Column("followers_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "users", sa.Column("following_count", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "following_count")
    op.drop_column("users", "followers_count")
    op.drop_column("users", "avatar_url")
    op.drop_column("posts", "likes_count")
    op.drop_column("posts", "author_avatar_url")
    # ### end Alembic commands ###
