"""remove author_nickname and author_gender from posts

Revision ID: 7bdf28775e83
Revises: 36696b9825b5
Create Date: 2026-03-04 17:51:32.417767

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bdf28775e83"
down_revision: str | None = "36696b9825b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "author_gender")
    op.drop_column("posts", "author_nickname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("author_nickname", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "posts", sa.Column("author_gender", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
