"""remove author_nickname and author_gender from posts

Revision ID: 7bdf28775e83
Revises: 36696b9825b5
Create Date: 2026-03-04 17:51:32.417767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7bdf28775e83'
down_revision: Union[str, None] = '36696b9825b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_gender')
    op.drop_column('posts', 'author_nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('author_gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###