"""create_follows_table

Revision ID: 86deffe96aa3
Revises: 7bdf28775e83
Create Date: 2026-03-04 21:16:00.957459

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "86deffe96aa3"
down_revision: str | None = "7bdf28775e83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
