"""update_reports_reply_foreign_key_to_posts

Revision ID: 9cfc96c8742c
Revises: cc6e0503aa7f
Create Date: 2026-03-15 19:09:27.346729

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9cfc96c8742c"
down_revision: str | None = "cc6e0503aa7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First update foreign key constraints to point to posts table
    op.drop_constraint(op.f("notifications_reply_id_fkey"), "notifications", type_="foreignkey")
    op.create_foreign_key(None, "notifications", "posts", ["reply_id"], ["id"])
    op.drop_constraint(op.f("reports_reply_id_fkey"), "reports", type_="foreignkey")
    op.create_foreign_key(None, "reports", "posts", ["reply_id"], ["id"])

    # Then drop the replies table and its indexes
    op.drop_index(op.f("ix_replies_parent_id"), table_name="replies")
    op.drop_index(op.f("ix_replies_post_id"), table_name="replies")
    op.drop_index(op.f("ix_replies_user_id"), table_name="replies")
    op.drop_table("replies")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reports", type_="foreignkey")  # type: ignore
    op.create_foreign_key(op.f("reports_reply_id_fkey"), "reports", "replies", ["reply_id"], ["id"])
    op.drop_constraint(None, "notifications", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        op.f("notifications_reply_id_fkey"), "notifications", "replies", ["reply_id"], ["id"]
    )
    op.create_table(
        "replies",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("post_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(length=300), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("likes_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("replies_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["replies.id"], name=op.f("replies_parent_id_fkey")),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], name=op.f("replies_post_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("replies_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("replies_pkey")),
    )
    op.create_index(op.f("ix_replies_user_id"), "replies", ["user_id"], unique=False)
    op.create_index(op.f("ix_replies_post_id"), "replies", ["post_id"], unique=False)
    op.create_index(op.f("ix_replies_parent_id"), "replies", ["parent_id"], unique=False)
    # ### end Alembic commands ###
