"""update_notifications_reply_foreign_key_to_posts

Revision ID: cc6e0503aa7f
Revises: e29ff9b5cb90
Create Date: 2026-03-15 19:06:31.606277

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc6e0503aa7f"
down_revision: str | None = "e29ff9b5cb90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update notifications table foreign key from replies to posts
    op.drop_constraint("notifications_reply_id_fkey", "notifications", type_="foreignkey")
    op.create_foreign_key(None, "notifications", "posts", ["reply_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert notifications table foreign key back to replies
    op.drop_constraint(None, "notifications", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "notifications_reply_id_fkey", "notifications", "replies", ["reply_id"], ["id"]
    )
    # ### end Alembic commands ###
