"""add_reply_likes_and_nested_replies

Revision ID: ccb42b79b420
Revises: f614b8efbc14
Create Date: 2026-03-15 16:22:38.699221

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccb42b79b420"
down_revision: str | None = "f614b8efbc14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reply_likes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reply_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reply_id"],
            ["replies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reply_likes_reply_id"), "reply_likes", ["reply_id"], unique=False)
    op.create_index(op.f("ix_reply_likes_user_id"), "reply_likes", ["user_id"], unique=False)
    op.add_column("replies", sa.Column("parent_id", sa.Uuid(), nullable=True))
    # Add columns with server_default first, then remove the default
    op.add_column(
        "replies",
        sa.Column("likes_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "replies",
        sa.Column("replies_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("replies", "likes_count", server_default=None)
    op.alter_column("replies", "replies_count", server_default=None)
    op.create_index(op.f("ix_replies_parent_id"), "replies", ["parent_id"], unique=False)
    op.create_foreign_key(None, "replies", "replies", ["parent_id"], ["id"])
    op.alter_column(
        "reports",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reports",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "replies", type_="foreignkey")  # type: ignore
    op.drop_index(op.f("ix_replies_parent_id"), table_name="replies")
    op.drop_column("replies", "replies_count")
    op.drop_column("replies", "likes_count")
    op.drop_column("replies", "parent_id")
    op.drop_index(op.f("ix_reply_likes_user_id"), table_name="reply_likes")
    op.drop_index(op.f("ix_reply_likes_reply_id"), table_name="reply_likes")
    op.drop_table("reply_likes")
    # ### end Alembic commands ###
