"""integrate_replies_into_posts

Revision ID: e29ff9b5cb90
Revises: ccb42b79b420
Create Date: 2026-03-15 18:43:27.103535

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e29ff9b5cb90"
down_revision: str | None = "ccb42b79b420"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.add_column("posts", sa.Column("root_id", sa.Uuid(), nullable=True))
    op.add_column(
        "posts", sa.Column("replies_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.create_index(op.f("ix_posts_parent_id"), "posts", ["parent_id"], unique=False)
    op.create_index(op.f("ix_posts_root_id"), "posts", ["root_id"], unique=False)
    op.create_foreign_key(None, "posts", "posts", ["root_id"], ["id"])
    op.create_foreign_key(None, "posts", "posts", ["parent_id"], ["id"])

    # Migrate data from replies to posts
    connection = op.get_bind()

    # First, insert all replies as posts
    connection.execute(
        sa.text("""
        INSERT INTO posts (id, user_id, content, parent_id, root_id, created_at, updated_at, replies_count, author_status, author_age_range, author_avatar_url, likes_count)
        SELECT
            r.id,
            r.user_id,
            r.content,
            CASE
                WHEN r.parent_id IS NOT NULL THEN r.parent_id  -- Nested reply
                ELSE r.post_id  -- First-level reply
            END as parent_id,
            r.post_id as root_id,  -- Always use the original post as root
            r.created_at,
            r.created_at,  -- Use created_at as updated_at since replies don't have updated_at
            COALESCE(r.replies_count, 0),
            u.status,
            u.age_range,
            u.avatar_url,
            COALESCE(r.likes_count, 0)
        FROM replies r
        JOIN users u ON r.user_id = u.id
    """)
    )

    # Update replies_count for posts that have replies
    connection.execute(
        sa.text("""
        UPDATE posts p
        SET replies_count = (
            SELECT COUNT(*)
            FROM posts p2
            WHERE p2.parent_id = p.id
        )
        WHERE EXISTS (
            SELECT 1
            FROM posts p2
            WHERE p2.parent_id = p.id
        )
    """)
    )

    op.drop_constraint(op.f("reply_likes_reply_id_fkey"), "reply_likes", type_="foreignkey")
    op.create_foreign_key(None, "reply_likes", "posts", ["reply_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reply_likes", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        op.f("reply_likes_reply_id_fkey"), "reply_likes", "replies", ["reply_id"], ["id"]
    )
    op.drop_constraint(None, "posts", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "posts", type_="foreignkey")  # type: ignore
    op.drop_index(op.f("ix_posts_root_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_parent_id"), table_name="posts")
    op.drop_column("posts", "replies_count")
    op.drop_column("posts", "root_id")
    op.drop_column("posts", "parent_id")
    # ### end Alembic commands ###
