"""update_reports_table_schema

Revision ID: f614b8efbc14
Revises: 382cbc49cab5
Create Date: 2026-03-14 00:27:58.247188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f614b8efbc14'
down_revision: Union[str, None] = '382cbc49cab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ENUM types first (only if they don't exist)
    op.execute("DO $$ BEGIN CREATE TYPE reporttype AS ENUM ('SPAM', 'HARASSMENT', 'INAPPROPRIATE', 'OTHER'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE reportstatus AS ENUM ('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE userstatus AS ENUM ('IN_LOVE', 'HEARTBROKEN', 'SEEKING'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PRIVATE'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE agerange AS ENUM ('TEENS', 'TWENTIES', 'THIRTIES', 'FORTIES', 'FIFTIES_PLUS'); EXCEPTION WHEN duplicate_object THEN null; END $$")

    op.drop_index(op.f('idx_banned_words_active'), table_name='banned_words', postgresql_where='(is_active = true)')
    op.drop_table('banned_words')
    op.drop_constraint(op.f('conversation_participants_conversation_id_user_id_key'), 'conversation_participants', type_='unique')
    op.drop_index(op.f('idx_conv_participants_conv'), table_name='conversation_participants')
    op.drop_index(op.f('idx_conv_participants_user'), table_name='conversation_participants')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('idx_dm_conversation'), table_name='direct_messages')
    op.drop_index(op.f('idx_dm_sender'), table_name='direct_messages')
    op.create_index(op.f('ix_direct_messages_conversation_id'), 'direct_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_direct_messages_sender_id'), 'direct_messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('direct_messages_sender_id_fkey'), 'direct_messages', type_='foreignkey')
    op.drop_constraint(op.f('direct_messages_conversation_id_fkey'), 'direct_messages', type_='foreignkey')
    op.create_foreign_key(None, 'direct_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'direct_messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(op.f('follows_follower_id_following_id_key'), 'follows', type_='unique')
    op.drop_index(op.f('idx_follows_follower'), table_name='follows')
    op.drop_index(op.f('idx_follows_following'), table_name='follows')
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.drop_constraint(op.f('follows_follower_id_fkey'), 'follows', type_='foreignkey')
    op.drop_constraint(op.f('follows_following_id_fkey'), 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['following_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.drop_index(op.f('idx_likes_post'), table_name='likes')
    op.drop_index(op.f('idx_likes_user'), table_name='likes')
    op.drop_constraint(op.f('likes_user_id_post_id_key'), 'likes', type_='unique')
    op.create_index(op.f('ix_likes_post_id'), 'likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.drop_constraint(op.f('likes_post_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_personality_primary'), table_name='personality_results')
    op.drop_index(op.f('idx_personality_user'), table_name='personality_results')
    op.drop_constraint(op.f('personality_results_user_id_key'), 'personality_results', type_='unique')
    op.create_index(op.f('ix_personality_results_primary_type'), 'personality_results', ['primary_type'], unique=False)
    op.create_index(op.f('ix_personality_results_user_id'), 'personality_results', ['user_id'], unique=True)
    op.drop_constraint(op.f('personality_results_user_id_fkey'), 'personality_results', type_='foreignkey')
    op.create_foreign_key(None, 'personality_results', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_posts_created_at'), table_name='posts')
    op.drop_index(op.f('idx_posts_user_id'), table_name='posts')
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_replies_post_id'), table_name='replies')
    op.drop_index(op.f('idx_replies_user_id'), table_name='replies')
    op.create_index(op.f('ix_replies_post_id'), 'replies', ['post_id'], unique=False)
    op.create_index(op.f('ix_replies_user_id'), 'replies', ['user_id'], unique=False)
    op.drop_constraint(op.f('replies_post_id_fkey'), 'replies', type_='foreignkey')
    op.drop_constraint(op.f('replies_user_id_fkey'), 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'replies', 'posts', ['post_id'], ['id'])
    op.drop_column('replies', 'updated_at')
    op.add_column('reports', sa.Column('report_type', sa.Enum('SPAM', 'HARASSMENT', 'INAPPROPRIATE', 'OTHER', name='reporttype'), nullable=False, server_default='OTHER'))
    op.add_column('reports', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('reviewer_id', sa.Uuid(), nullable=True))
    op.add_column('reports', sa.Column('reviewer_comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('reports', 'reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               nullable=False)
    # Convert status column to enum type with explicit casting
    op.execute("ALTER TABLE reports ALTER COLUMN status TYPE reportstatus USING status::text::reportstatus")
    op.drop_index(op.f('idx_reports_reporter'), table_name='reports')
    op.drop_index(op.f('idx_reports_status'), table_name='reports')
    op.create_index(op.f('ix_reports_post_id'), 'reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_reports_reply_id'), 'reports', ['reply_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_constraint(op.f('reports_reply_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_user_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_post_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_reporter_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'replies', ['reply_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['reviewer_id'], ['id'])
    op.drop_column('reports', 'resolved_at')
    op.drop_column('reports', 'type')
    # usersテーブルのstatusカラムをuserstatusENUMに変更（defaultを一旦削除してから型変更）
    op.execute("ALTER TABLE users ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE userstatus USING status::text::userstatus")
    op.execute("ALTER TABLE users ALTER COLUMN status SET DEFAULT 'SEEKING'::userstatus")
    # usersテーブルのgenderカラムをgenderENUMに変更（defaultを一旦削除してから型変更）
    op.execute("ALTER TABLE users ALTER COLUMN gender DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN gender TYPE gender USING gender::text::gender")
    op.execute("ALTER TABLE users ALTER COLUMN gender SET DEFAULT 'PRIVATE'::gender")
    # usersテーブルのage_rangeカラムをagerangeENUMに変更
    op.execute("ALTER TABLE users ALTER COLUMN age_range TYPE agerange USING age_range::text::agerange")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'age_range',
               existing_type=sa.Enum('TEENS', 'TWENTIES', 'THIRTIES', 'FORTIES', 'FIFTIES_PLUS', name='agerange'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', 'PRIVATE', name='gender'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'private'::character varying"))
    op.alter_column('users', 'status',
               existing_type=sa.Enum('IN_LOVE', 'HEARTBROKEN', 'SEEKING', name='userstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'seeking'::character varying"))
    op.add_column('reports', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_reporter_id_fkey'), 'reports', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reports_post_id_fkey'), 'reports', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reports_user_id_fkey'), 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reports_reply_id_fkey'), 'reports', 'replies', ['reply_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reply_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_post_id'), table_name='reports')
    op.create_index(op.f('idx_reports_status'), 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_reports_reporter'), 'reports', ['reporter_id'], unique=False)
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED', name='reportstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('reports', 'reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'reviewer_comment')
    op.drop_column('reports', 'reviewer_id')
    op.drop_column('reports', 'reviewed_at')
    op.drop_column('reports', 'report_type')
    op.add_column('replies', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key(op.f('replies_user_id_fkey'), 'replies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('replies_post_id_fkey'), 'replies', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_replies_user_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_post_id'), table_name='replies')
    op.create_index(op.f('idx_replies_user_id'), 'replies', ['user_id'], unique=False)
    op.create_index(op.f('idx_replies_post_id'), 'replies', ['post_id'], unique=False)
    op.alter_column('replies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.create_index(op.f('idx_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_posts_created_at'), 'posts', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('posts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('posts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'personality_results', type_='foreignkey')
    op.create_foreign_key(op.f('personality_results_user_id_fkey'), 'personality_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_personality_results_user_id'), table_name='personality_results')
    op.drop_index(op.f('ix_personality_results_primary_type'), table_name='personality_results')
    op.create_unique_constraint(op.f('personality_results_user_id_key'), 'personality_results', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_personality_user'), 'personality_results', ['user_id'], unique=False)
    op.create_index(op.f('idx_personality_primary'), 'personality_results', ['primary_type'], unique=False)
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('likes_post_id_fkey'), 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_post_id'), table_name='likes')
    op.create_unique_constraint(op.f('likes_user_id_post_id_key'), 'likes', ['user_id', 'post_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_likes_user'), 'likes', ['user_id'], unique=False)
    op.create_index(op.f('idx_likes_post'), 'likes', ['post_id'], unique=False)
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(op.f('follows_following_id_fkey'), 'follows', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('follows_follower_id_fkey'), 'follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.create_index(op.f('idx_follows_following'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('idx_follows_follower'), 'follows', ['follower_id'], unique=False)
    op.create_unique_constraint(op.f('follows_follower_id_following_id_key'), 'follows', ['follower_id', 'following_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'direct_messages', type_='foreignkey')
    op.drop_constraint(None, 'direct_messages', type_='foreignkey')
    op.create_foreign_key(op.f('direct_messages_conversation_id_fkey'), 'direct_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('direct_messages_sender_id_fkey'), 'direct_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_direct_messages_sender_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_conversation_id'), table_name='direct_messages')
    op.create_index(op.f('idx_dm_sender'), 'direct_messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_dm_conversation'), 'direct_messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_conv_participants_user'), 'conversation_participants', ['user_id'], unique=False)
    op.create_index(op.f('idx_conv_participants_conv'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_unique_constraint(op.f('conversation_participants_conversation_id_user_id_key'), 'conversation_participants', ['conversation_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('banned_words',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('banned_words_pkey')),
    sa.UniqueConstraint('word', name=op.f('banned_words_word_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_banned_words_active'), 'banned_words', ['is_active'], unique=False, postgresql_where='(is_active = true)')

    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS agerange")
    op.execute("DROP TYPE IF EXISTS gender")
    op.execute("DROP TYPE IF EXISTS userstatus")
    op.execute("DROP TYPE IF EXISTS reportstatus")
    op.execute("DROP TYPE IF EXISTS reporttype")
    # ### end Alembic commands ###